#monitor=DP-3,preferred,0x0,1
#monitor=DP-2,preferred,1920x0,1
#monitor=HDMI-A-1,preferred,1920x0,1

monitor=HDMI-A-1,preferred,0x0,1
# monitor=DP-3,3440x1440@60,1920x0,1

monitor=eDP-1,preferred,0x0,2
# monitor=DP-1,preferred,1920x0,1.5
# monitor=DP-2,preferred,0x0,2,mirror,eDP-1
monitor=DP-3,preferred,1920x0,1.5