#!/bin/sh

# This script displays battery icon according to the charge level and charging state

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `acpi`

bat=$(acpi -b)
state=$(echo ${bat} | awk '{print $3}')

if [[ "$state" = "Not" ]]; then
    level=$(echo ${bat} | awk '{print $5}')
    level=${level::-1}
    
else
    level=$(echo ${bat} | awk '{print $4}')
    if [[ "$state" == *"Unknown"* ]]; then
        level=${level::-1}
    else
        if [[ "$level" == "100%" ]]; then
            level=${level::-1}
        else
            level=${level::-2}
        fi
    fi
fi

available() {
    if [["$bat" == *"until"*]]; then
        echo true
    else
        echo false
    fi
}

icon() {
    if [[ "$bat" == *"until"* ]]; then
        
        if [[ "$level" -ge "80" ]]; then
            echo " "
            elif [[ "$level" -ge "60" ]]; then
            echo " "
            elif [[ "$level" -ge "40" ]]; then
            echo " "
            elif [[ "$level" -ge "20" ]]; then
            echo " "
        else
            echo " "
        fi
    else
        if [[ "$level" -ge "80" ]]; then
            echo "  "
            elif [[ "$level" -ge "60" ]]; then
            echo "  "
            elif [[ "$level" -ge "40" ]]; then
            echo "  "
            elif [[ "$level" -ge "20" ]]; then
            echo "  "
        else
            echo "󱉝"
        fi
    fi
}

color() {
    if [[ "$bat" == *"until"* ]]; then
        if [[ "$state" == *"Discharging"* ]]; then
            local green=$(echo "255" | awk '{printf "%d\n", $1 * (100 - ${value}) / 100}')
            local red=$(echo "255" | awk '{printf "%d\n", $1 * ${value} / 100}')

            printf "#%02x%02x%02x\n" "$red" "$green" "00"
        elif [[ "$state" == *"Charging"* ]]; then
            echo "#f9dc5c"
        else
            echo "#4c566a"
        fi
    else
        echo "#4c566a"
    fi
}

text() {
    echo "${state::-1}"
}

class() {
    if [[ "$bat" == *"until"* ]]; then
        echo ""
    else
        echo " "
    fi
}



if [[ $1 = "-l" ]]; then
    echo "${level}%"
elif [[ $1 == "-c" ]]; then
    class
elif [[ $1 = "-i" ]]; then
    icon
elif [[ $1 == "-a" ]]; then
    available
elif [[ $1 == "-t" ]]; then
    text
elif [[ $1 == "--color" ]]; then
    color
fi