#!/bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

toggle_system() {
    is_open=$(eww get system-menu-open)

    if [[ $is_open == true ]]; then
        $(eww update system-menu-open=false)
        $(eww close system-menu)
    else
        $(eww open system-menu)
        $(eww update system-menu-open=true)
    fi
}

toggle_power() {
    is_open=$(eww get power-menu-open)

    if [[ $is_open == true ]]; then
        $(eww update power-menu-open=false)
        $(eww close power-menu)
    else
        $(eww open power-menu)
        $(eww update power-menu-open=true)
    fi
}

toggle_pocket() {
    is_open=$(eww get pocket-menu-open)

    if [[ $is_open == true ]]; then
        $(eww update pocket-menu-open=false)
        $(eww close pocket-menu)
    else
        $(eww open pocket-menu)
        # current_playing_player_index=$($SCRIPT_DIR/music --current-playing-player-index)
        $(eww update active-player-index=$current_playing_player_index)
        $(eww update pocket-menu-open=true)
    fi
}

if [[ $1 == "--toggle-system" ]]; then
    toggle_system
elif [[ $1 == "--toggle-power" ]]; then
    toggle_power
elif [[ $1 == "--toggle-pocket" ]]; then
    toggle_pocket
fi