#!/bin/bash

status() {

    readarray -t player_names < <(playerctl --list-all)

    local player_names_json="["
    local first=true

    for ((i=0; i < "${#player_names[@]}"; i++)); do
        player_index="$i"
        player_total="${#player_names[@]}"
        player_name="${player_names[i]}"
        player_status=$(playerctl status --player=$player_name 2>/dev/null)
        player_volume=$(playerctl volume --player=$player_name 2>/dev/null)
        player_loop=$(playerctl loop --player=$player_name 2>/dev/null)
        player_shuffle=$(playerctl shuffle --player=$player_name 2>/dev/null)
        player_position=$(playerctl position --player=$player_name 2>/dev/null)
        player_set_play="playerctl play --player=$player_name"
        player_set_pause="playerctl pause --player=$player_name"
        player_set_play_pause="playerctl play-pause --player=$player_name"
        player_set_stop="playerctl stop --player=$player_name"
        player_set_next="playerctl next --player=$player_name"
        player_set_previous="playerctl previous --player=$player_name"
        player_set_position="playerctl position --player=$player_name"
        player_set_volume="playerctl volume --player=$player_name"
        player_set_loop="playerctl loop --player=$player_name"
        player_set_shuffle="playerctl shuffle --player=$player_name"
        player_metadata_length=$(playerctl metadata --player=$player_name mpris:length 2>/dev/null)
        player_metadata_art_url=$(playerctl metadata --player=$player_name mpris:artUrl 2>/dev/null)
        player_metadata_album=$(playerctl metadata --player=$player_name xesam:album 2>/dev/null)
        player_metadata_artist=$(playerctl metadata --player=$player_name xesam:artist 2>/dev/null)
        player_metadata_title=$(playerctl metadata --player=$player_name xesam:title 2>/dev/null)

        if [[ -z "$player_volume" ]]; then
            player_volume=0
        fi

        if [[ -z "$player_metadata_length" ]]; then
            player_metadata_length=0
        else
            player_metadata_length=$(($player_metadata_length / 1000000))
        fi

        if [[ -z "$player_position" ]]; then
            player_position=0
        fi


        player_length=$player_metadata_length

        player_metadata="
        {
            \"art_url\": \"$player_metadata_art_url\",
            \"album\": \"$player_metadata_album\",
            \"artist\": \"$player_metadata_artist\",
            \"title\": \"$player_metadata_title\"
        }
        "
        player="
        {
            \"index\": $player_index,
            \"total\": $player_total,
            \"name\": \"$player_name\",
            \"status\": \"$player_status\",
            \"volume\": $player_volume,
            \"loop\": \"$player_loop\",
            \"shuffle\": \"$player_shuffle\",
            \"position\": \"$player_position\",
            \"length\": \"$player_length\",
            \"set_play\": \"$player_set_play\",
            \"set_pause\": \"$player_set_pause\",
            \"set_play_pause\": \"$player_set_play_pause\",
            \"set_stop\": \"$player_set_stop\",
            \"set_next\": \"$player_set_next\",
            \"set_previous\": \"$player_set_previous\",
            \"set_position\": \"$player_set_position\",
            \"set_volume\": \"$player_set_volume\",
            \"set_loop\": \"$player_set_loop\",
            \"set_shuffle\": \"$player_set_shuffle\",
            \"metadata\": $player_metadata
        }
        "

        if [ "$first" = false ]; then
            player_names_json+=", "
        else
            first=false
        fi

        player_names_json+="$player"
    done
    player_names_json+="]"

    echo "$player_names_json"
}

current_playing_player_index() {
    readarray -t player_stati < <(playerctl status --all-players)

    current_playing_player=0
    for ((i=0; i < "${#player_stati[@]}"; i++)); do
        if [[ ${player_stati[i]} == "Playing" ]]; then
            current_playing_player=$i
            break
        fi
    done

    echo $current_playing_player
}

if [[ $1 == "--status" ]]; then
    status
elif [[ $1 == "--current-playing-player-index" ]]; then
    current_playing_player_index
fi