#!/usr/bin/env bash
WIFI_INTERFACE=$(iwconfig 2>/dev/null | grep -o '^[a-zA-Z0-9]*' | grep -E '^w' | head -1)
ETHERNET_INTERFACE=$(ip -o link show 2>/dev/null | awk '{print $2}' | grep -E '^e' | head -1)
ACTIVE_INTERFACE=$(ip route | awk '/^default/ {print $5}')
STATUS=$(nmcli | grep ${ACTIVE_INTERFACE} | awk 'FNR == 1 {print $2}')
SSID=$(iwgetid | awk -F '"' '{ print $2 }')
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

toggle() {
    if [[ $STATUS == "connected" ]]; then
        nmcli radio wifi off
        notify-send --icon=window-close --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
    else
        nmcli radio wifi on
        notify-send --icon=checkmark --urgency=normal "Wi-Fi" "Wi-Fi has been turned on, you are back online!"
    fi
}

icon() {
    if [[ $ACTIVE_INTERFACE == $WIFI_INTERFACE ]]; then
        if [[ "$STRENGTH" -ge "80" ]]; then
            echo "󰤨"
        elif [[ "$STRENGTH" -ge "60" ]]; then
            echo "󰤥"
        elif [[ "$STRENGTH" -ge "40" ]]; then
            echo "󰤢"
        elif [[ "$STRENGTH" -ge "20" ]]; then
            echo "󰤟"
        elif [[ "$STRENGTH" -ge "0" ]]; then
            echo "󰤯"
        else
            echo "󰤭"
        fi
    elif [[ $ACTIVE_INTERFACE == $ETHERNET_INTERFACE ]]; then
        echo "󰈀"
    else
        echo "󰤭"
    fi
}

status() {
    if [[ $STATUS == "connected" ]]; then
        echo $SSID
    else
        echo Disconnected
    fi
}

class(){
    if [[ $STATUS == "connected" ]]; then
        echo "󰤨"
    else
        echo "󰤭"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
elif [[ $1 == "--class" ]]; then
    class
fi

