#!/usr/bin/env bash
MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
toggle() {
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

icon() {
    if [ $MUTED == "no" ]; then
        echo "󰕾"
    else
        echo "󰖁"
    fi
}

status() {
    if [ $MUTED == "no" ]; then
        echo "On"
    else
        echo "Off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
