#!/bin/bash

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_hex=${cache_dir}/weather.color
cache_weather_icon=${cache_dir}/weather-icon

## Weather data
KEY="7e6ed49a1a7b802ad1299faa3a5f008d"
ID="2802361"
UNIT="metric"	# Available options : 'metric' or 'imperial'

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p ${cache_dir}
fi

refetch_data() {
	time_since_last_fetch=$(date +%s)

	echo $time_since_last_fetch > "$cache_dir/time_since_last_fetch"

	weather=`curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID="$KEY"&id="$ID"&units="$UNIT""`

	if [ ! -z "$weather" ]; then
		weather_temp=`echo "$weather" | jq ".main.temp" | cut -d "." -f 1`
		weather_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
		weather_description=`echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g"`

		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "50n"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "01d"  ]; then
			weather_icon=" "
			weather_hex="#e0af68"
		elif [ "$weather_icon_code" == "01n"  ]; then
			weather_icon=" "
			weather_hex="#c0caf5"
		elif [ "$weather_icon_code" == "02d"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "02n"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "03d"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "03n"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "04d"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "04n"  ]; then
			weather_icon=" "
			weather_hex="#7aa2f7"
		elif [ "$weather_icon_code" == "09d"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		elif [ "$weather_icon_code" == "09n"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		elif [ "$weather_icon_code" == "10d"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		elif [ "$weather_icon_code" == "10n"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		elif [ "$weather_icon_code" == "11d"  ]; then
			weather_icon=""
			weather_hex="#ff9e64"
		elif [ "$weather_icon_code" == "11n"  ]; then
			weather_icon=""
			weather_hex="#ff9e64"
		elif [ "$weather_icon_code" == "13d"  ]; then
			weather_icon=" "
			weather_hex="#c0caf5"
		elif [ "$weather_icon_code" == "13n"  ]; then
			weather_icon=" "
			weather_hex="#c0caf5"
		elif [ "$weather_icon_code" == "40d"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		elif [ "$weather_icon_code" == "40n"  ]; then
			weather_icon=" "
			weather_hex="#7dcfff"
		else 
			weather_icon=" "
			weather_hex="#c0caf5"
		fi
	else
		weather_temp="0"
		weather_icon=""
		weather_description="No weather"
	fi

	echo $weather_icon > "$cache_dir/weather-icon"
	echo $weather_temp > "$cache_dir/weather-degree"
	echo $weather_hex > "$cache_dir/weather.color"
	echo $weather_description > "$cache_dir/weather-stat"
}

data_needs_refetching() {
	time_since_last_fetch=$(cat "$cache_dir/time_since_last_fetch")
	time_now=$(date +%s)

	time_delta=$(($time_now - $time_since_last_fetch))

	if (( $time_delta > 600 )); then 
		refetch_data
	fi
}

weather_icon() {
	cat "$cache_dir/weather-icon"
}

weather_temp() {
	cat "$cache_dir/weather-degree"
}

weather_stat() {
	cat "$cache_dir/weather-stat"
}

weather_hex() {
	cat "$cache_dir/weather.color"
}

## Execute
if [[ "$1" == "--icon" ]]; then
	data_needs_refetching && weather_icon
elif [[ "$1" == "--temp" ]]; then
	data_needs_refetching && weather_temp
elif [[ "$1" == "--stat" ]]; then
	data_needs_refetching && weather_stat
elif [[ "$1" == "--hex" ]]; then
	data_needs_refetching && weather_hex
fi